"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.newDefaultLogn = exports.newDefaultLog = exports.newLogCopy = exports.levelToString = exports.isLevelEnabled = exports.Level = void 0;
var level_1 = require("./level");
Object.defineProperty(exports, "Level", { enumerable: true, get: function () { return level_1.Level; } });
Object.defineProperty(exports, "isLevelEnabled", { enumerable: true, get: function () { return level_1.isLevelEnabled; } });
Object.defineProperty(exports, "levelToString", { enumerable: true, get: function () { return level_1.levelToString; } });
var log_1 = require("./log");
Object.defineProperty(exports, "newLogCopy", { enumerable: true, get: function () { return log_1.newLogCopy; } });
Object.defineProperty(exports, "newDefaultLog", { enumerable: true, get: function () { return log_1.newDefaultLog; } });
Object.defineProperty(exports, "newDefaultLogn", { enumerable: true, get: function () { return log_1.newDefaultLogn; } });
